export const GRUPOS_ACTIVOS_FIJOS = [
  {
    codigo: 'EDIF',
    nombre: 'Edificaciones y Construcciones',
    descripcion: 'Edificios, locales, construcciones e instalaciones fijas',
    vidaUtilMinima: 20,
    vidaUtilMaxima: 33,
    tasaDepreciacionMinima: 3,
    tasaDepreciacionMaxima: 5,
  },
  {
    codigo: 'MAQIND',
    nombre: 'Maquinaria y Equipo Industrial',
    descripcion: 'Maquinaria de producción, equipos industriales, herramientas motorizadas',
    vidaUtilMinima: 6,
    vidaUtilMaxima: 10,
    tasaDepreciacionMinima: 10,
    tasaDepreciacionMaxima: 15,
  },
  {
    codigo: 'TRANSP',
    nombre: 'Equipos de Transporte',
    descripcion: 'Vehículos de transporte de carga, pasajeros, montacargas, etc.',
    vidaUtilMinima: 4,
    vidaUtilMaxima: 5,
    tasaDepreciacionMinima: 20,
    tasaDepreciacionMaxima: 25,
  },
  {
    codigo: 'MOB',
    nombre: 'Mobiliario y Equipo de Oficina',
    descripcion: 'Muebles, aires acondicionados, equipos de oficina en general',
    vidaUtilMinima: 6,
    vidaUtilMaxima: 10,
    tasaDepreciacionMinima: 10,
    tasaDepreciacionMaxima: 15,
  },
  {
    codigo: 'COMP',
    nombre: 'Equipos de Computación',
    descripcion: 'Computadoras, servidores, impresoras, redes, equipos informáticos',
    vidaUtilMinima: 3,
    vidaUtilMaxima: 4,
    tasaDepreciacionMinima: 25,
    tasaDepreciacionMaxima: 33,
  },
  {
    codigo: 'INSTR',
    nombre: 'Instrumentos y Herramientas',
    descripcion: 'Instrumentos de medición, herramientas manuales, equipos de laboratorio',
    vidaUtilMinima: 5,
    vidaUtilMaxima: 8,
    tasaDepreciacionMinima: 12,
    tasaDepreciacionMaxima: 20,
  },
  {
    codigo: 'EQMED',
    nombre: 'Equipos Médicos',
    descripcion: 'Equipos de diagnóstico, tratamiento, laboratorio clínico',
    vidaUtilMinima: 5,
    vidaUtilMaxima: 8,
    tasaDepreciacionMinima: 12,
    tasaDepreciacionMaxima: 20,
  },
  {
    codigo: 'OTROS',
    nombre: 'Otros Activos Fijos',
    descripcion: 'Activos no clasificados en las categorías anteriores',
    vidaUtilMinima: 3,
    vidaUtilMaxima: 10,
    tasaDepreciacionMinima: 10,
    tasaDepreciacionMaxima: 33,
  },
];
